version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: testgen-postgres
    environment:
      POSTGRES_DB: testgen_db
      POSTGRES_USER: testgen
      POSTGRES_PASSWORD: testgen123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testgen -d testgen_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: testgen-backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://testgen:testgen123@postgres:5432/testgen_db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/generated-tests:/app/generated-tests
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: testgen-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
